DROP SCHEMA IF EXISTS tp CASCADE;

CREATE SCHEMA IF NOT EXISTS tp;

CREATE TABLE IF NOT EXISTS tp.users (
    id SERIAL PRIMARY KEY,
    nickname VARCHAR UNIQUE NOT NULL,
    fullname VARCHAR NOT NULL,
    about TEXT,
    email VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS tp.forum (
    id SERIAL PRIMARY KEY,
    title VARCHAR NOT NULL,
    slug VARCHAR UNIQUE NOT NULL,
    posts INTEGER DEFAULT 0,
    threads INTEGER DEFAULT 0,

    user_id INTEGER REFERENCES tp.users NOT NULL 
);
